### ISSUE TITLE
Remove unnecessary copying step

### ISSUE THREAD

**Issue by finorix079** [cladular/ipfs-add-folder#10]
It seems the current process is to upload it to the root directory of IPFS, and then copy it into a folder. I think we can use the "route" to upload the files directly into the folder we want.

**Comment by ItayPodhajcer** [comment]
Hi,

The original implementation was done about three years ago, so it makes sense that things have changed (like `addAll` that didn't exist then).
Since then, only security patches and bug fixes were applied to reduce the chance of regressions in the code, so unless it falls into one of those two categories, no changes will be performed.

Additionally, I can't seem to find any reference to using `route` while adding files in the official core API spec: https://github.com/ipfs/js-ipfs/tree/master/docs/core-api.
